package ru.kfu.bot.service.model;

public enum BotState {
    DEFAULT,

    AWAITING_AFFINE_COUNT,
    AWAITING_SYMMETRY_COUNT,
    AWAITING_SAMPLES,
    AWAITING_ITERATIONS,
    AWAITING_IMAGE_WIDTH,
    AWAITING_IMAGE_HEIGHT,
    AWAITING_RECT_X,
    AWAITING_RECT_Y,
    AWAITING_RECT_WIDTH,
    AWAITING_RECT_HEIGHT,
    AWAITING_TRANSFORMATION_TYPES,

    AWAITING_HISTORY_CONFIG
}
